chore: update docs #ntrn-1
neutron-org/neutron-docs pull request #100
Opened 2023-07-20 15:29 UTC by NeverHappened

2023-08-01 12:58 UTC, pr0n00gler submitted a review, later dismissed

2023-08-01 15:42 UTC, foxpy requested changes

2023-08-01 15:42 UTC, foxpy commented on docs/relaying/ibc-relayer.md
> +cargo install ibc-relayer-cli --bin hermes --locked --version 1.6.0
Welp, it is not required to clone hermes repo in order to install it

2023-08-10 10:48 UTC, pr0n00gler approved these changes

2023-08-11 15:20 UTC, sotnikov-s approved these changes

2023-08-11 15:20 UTC, sotnikov-s commented on docs/relaying/target-chain.md
> +# Prepare target chain RPC node for Relayer's usage
why is this page blank? 🤔

2023-08-15 08:57 UTC, NeverHappened commented on docs/relaying/target-chain.md
> +# Prepare target chain RPC node for Relayer's usage
TBH i don't know) And not sure what to write here

2023-08-15 09:02 UTC, foxpy approved these changes

2023-08-15 12:40 UTC, pr0n00gler approved these changes

2023-08-15 13:05 UTC, merged