chore: improve icq kv docs #ntrn-72
neutron-org/neutron-docs pull request #101
Opened 2023-07-26 15:46 UTC by NeverHappened

https://hadronlabs.atlassian.net/browse/NTRN-72

2023-08-11 11:30 UTC, pr0n00gler requested changes

2023-08-11 11:30 UTC, pr0n00gler commented on docs/tutorials/cosmwasm-icq.md
> +Usually we'll look into keeper.go (TODO: LINK) to see where and what kind of data it keeps in a store.
There is a couple of unfinished TODOs

2023-08-17 14:52 UTC, pr0n00gler submitted a review, later dismissed

2023-08-24 09:27 UTC, sotnikov-s commented on docs/tutorials/cosmwasm-icq.md
> +Then you can implement KVReconstruct like this:
could you please add some additional info on how to reconstruct values? it seems to be easy for contract info since there is a helper for it (the OsmisisContractIInfo::decode one), but how do I make my own one if there is no helper? e.g. I should get a value from the store and it's in hex encoded proto bytes, I should then decode it somehow to a structure. but how? now the guide seems more like the "how to draw an owl meme"
![image](https://github.com/neutron-org/neutron-docs/assets/34917380/ea8e7f7d-8f92-4c67-8fb7-a6835489ce4a)

2023-08-24 09:27 UTC, sotnikov-s commented on docs/tutorials/cosmwasm-icq.md
> +Then you can implement KVReconstruct like this:
there is a repo https://github.com/neutron-org/icq-compliance-officer which I used to get raw data from KV Store from tendermint for [reconstruct tests](https://github.com/neutron-org/neutron-sdk/blob/main/packages/neutron-sdk/src/interchain_queries/v045/testing.rs#L762) for neutron-sdk. I'd like to see here:
1. how construct custom keys to KV Store (you've already described it)
2. how to create a reconstruct handler for corresponding values (now missing): (the following is a rough suggestion) find the data model behind a key in corresponding cosmos-sdk module, describe it in Rust, implement a reconstruct where the raw value is decoded and unmarshalled into the defined model

2023-08-24 09:27 UTC, sotnikov-s commented on docs/tutorials/cosmwasm-icq.md
> +> WARN: if you find the wrong version of the module, key construction can change and you'll fail to query data
please elaborate. here is a [doc](https://www.notion.so/hadron/ICQ-to-cosmos-sdk-version-9a05319f13b5405a8d1fb4bb5e3919da?pvs=4#26312da725f349ca8ed3faa864a10094) that can help you in it: see how the `Storage models` are different for `v.0.45.11-ics` and for `v0.47.1`. you can use this difference as an example here in docs to emphasize importance

2023-08-24 11:48 UTC, NeverHappened commented on docs/relaying/icq-relayer.md
> +#### How query result submission works in Neutron ICQ module
Probably yes, I don't know I just followed this point in the task: `Add documentation section on how the kv data is returned on the host`.
@pr0n00gler WDYT?

2023-09-06 11:18 UTC, sotnikov-s commented on docs/tutorials/cosmwasm-icq.md
> +To construct the key, you can use run this code somewhere:
you can **use run** this code -> you can **use**? **run**? this code

2023-09-06 11:18 UTC, sotnikov-s commented on docs/tutorials/cosmwasm-icq.md
> +let addr = "osmo14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sq2r9g9";
please add used functions import to the top of the snippet

2023-09-06 11:18 UTC, sotnikov-s commented on docs/tutorials/cosmwasm-icq.md
> +> WARN: if you use different versions of the module to find data and actually run chain, key construction AND/OR data model can change and you'll fail to query data AND/OR deconstruct it!
WARN: if you use different versions of the module to find data and **actually run chain**

please rephrase, this is hard to understand

2023-09-15 06:45 UTC, sotnikov-s approved these changes

2023-10-04 09:54 UTC, pr0n00gler approved these changes

2023-10-07 06:37 UTC, sotnikov-s approved these changes

2023-10-07 06:38 UTC, merged