add docs for resubmit failure #ntrn-84
neutron-org/neutron-docs pull request #104
Opened 2023-08-23 08:52 UTC by NeverHappened

https://hadronlabs.atlassian.net/browse/NTRN-84

2023-08-23 11:29 UTC, pr0n00gler approved these changes

2023-08-23 11:29 UTC, pr0n00gler commented on docs/neutron/modules/contract-manager/overview.md
> +The only difference is that this SubmitHandler will be called not from relayer, so the gas limitations above do not apply.
```suggestion
The only difference is that this `SubmitHandler` will be called not from relayer, so the gas limitations above do not apply.
```

2023-10-15 00:34 UTC, foxpy commented on docs/neutron/modules/contract-manager/overview.md
> +To make sure there is no exploits with infinite recursion of IBC calls that call another IBC messages in sudo handler we use constant gas `LIMIT` to spent. If your contracts need to do intense comput
```suggestion
To make sure there are no exploits with infinite recursion of IBC messages which call other IBC messages in sudo handler we use constant gas `LIMIT` to spend. If your contracts need to do intense computational work in sudo handler, you can save the messages and do work later in a separate method.
```

2023-10-15 00:34 UTC, foxpy commented on docs/neutron/modules/contract-manager/overview.md
> +We give an ability to resubmit bindings through the contract that initiated the IBC transaction.
```suggestion
We provide an ability to resubmit bindings through the contract that initiated the IBC transaction.
```

2023-10-19 13:50 UTC, sotnikov-s requested changes

2023-10-25 10:29 UTC, sotnikov-s approved these changes

2023-10-27 12:29 UTC, pr0n00gler approved these changes

2023-11-02 12:09 UTC, merged