Neutron  v2.0.0 upgrade doc NTRN-137
neutron-org/neutron-docs pull request #133
Opened 2023-11-30 08:54 UTC by quasisamurai

I'm gonna use this branch as a base for [this](https://hadronlabs.atlassian.net/browse/NTRN-166) task

2023-11-30 12:37 UTC, pr0n00gler requested changes

2023-11-30 12:37 UTC, pr0n00gler commented on docs/neutron/v2-upgrade/overview.md
> +        - **Gas Counting Exclusion:** Removal of gas counting in the upgrade module's begin blocker for more consistent gas accounting.
Please attach a relevant PR in our SDK here

2023-11-30 12:37 UTC, pr0n00gler commented on docs/neutron/v2-upgrade/overview.md
> +        - **Optimized Slashing Calculation:** Backporting of slashing missed blocks calculation from sdk v0.50.
Please attach a relevant PR in our SDK here

2023-11-30 12:37 UTC, pr0n00gler commented on docs/neutron/v2-upgrade/overview.md
> +- **Smart-Contract Size Limit Increase:** Expansion of the binary size limit from 800KB to 3MB as [explained here](https://github.com/neutron-org/neutron/pull/320).
```suggestion
- **Smart-Contract Size Limit Increase:** Expansion of the binary size limit from 800KB to 1.6MB as [explained here](https://github.com/neutron-org/neutron/pull/320).
```

2023-11-30 12:37 UTC, pr0n00gler commented on docs/neutron/v2-upgrade/overview.md
> +- **Additional Improvements:** Various other technical modifications and advancements.
Please attach a link to wasmd 0.45 release with a changelog

2023-11-30 12:37 UTC, pr0n00gler commented on docs/neutron/v2-upgrade/overview.md
> +        - **Technical Enhancements:** Several minor yet impactful technical improvements.
Please attach a link to Cosmos SDK 0.47 release with a changelog

2023-11-30 12:37 UTC, pr0n00gler commented on docs/neutron/v2-upgrade/overview.md
> +- **BankHooks Activation:** Introduction of BankHooks for smart contracts handling token transfers, as detailed [here](https://github.com/neutron-org/neutron/blob/update-sdk47/x/tokenfactory/keeper/b
Would be better to provide link to our documentation which describes these hooks (not the code)

2023-11-30 12:37 UTC, pr0n00gler commented on docs/neutron/v2-upgrade/overview.md
> +- **New Fee Structure for ICA Creation:** Introduction of a fee system for developers creating ICAs on remote chains.
Please attach relevant PR's and links to our documentation

2023-12-01 08:31 UTC, quasisamurai commented on docs/neutron/v2-upgrade/overview.md
> +        - **Technical Enhancements:** Several minor yet impactful technical improvements.
it's already there, line `Access to the full changelog...`

2023-12-01 13:43 UTC, pr0n00gler requested changes
There is no mention of Duality integration in v2 release, pls add it

2023-12-01 13:43 UTC, pr0n00gler commented on docs/neutron/overview.md
> +Neutron has transitioned from cosmos-sdk v0.45 to the more advanced v0.47, encompassing significant improvements and custom adaptations. The key aspects of this upgrade include:
In different places you say  `cosmos-sdk`, `sdk`, `Cosmos SDK`. Let's use `Cosmos SDK` everywhere, pls

2023-12-01 13:43 UTC, pr0n00gler commented on docs/neutron/overview.md
> +### Updates
Let's rename it `Releases`

2023-12-01 13:43 UTC, pr0n00gler commented on docs/neutron/overview.md
> +<details> <summary> v2.0.0</summary>
`<details> <summary><b>v2.0.0</b></summary>`

2023-12-01 13:43 UTC, pr0n00gler commented on docs/neutron/overview.md
> +<details> <summary> v2.0.0</summary>
Also we need a link to a release page on Github

2023-12-01 13:46 UTC, pr0n00gler requested changes

2023-12-01 13:46 UTC, pr0n00gler commented on docs/neutron/overview.md
> +This section provides a comprehensive overview of the significant changes and updates in Neutron version 2, focusing on the upgrades to Cosmos SDK, Wasmd, and Neutron's internal modules.
Let's put an overview outside a spoiler, so users could see a small description of the release.
And under the spoiler there will be a full context of a release

2023-12-01 14:47 UTC, quasisamurai commented on docs/neutron/overview.md
> +Neutron has transitioned from cosmos-sdk v0.45 to the more advanced v0.47, encompassing significant improvements and custom adaptations. The key aspects of this upgrade include:
Duality docs are gonna be merged in this repo as I mentioned in PR header

2023-12-05 11:21 UTC, pr0n00gler requested changes

2023-12-05 11:21 UTC, pr0n00gler commented on docs/neutron/neutron-core-releases.md
> +- **New Fee Structure for ICA Creation:** [Introduction](https://github.com/neutron-org/neutron/pull/334) of a fee system for developers creating ICAs on remote chains. [Learn more](neutron/modules/i
**Learn more** link is 404

2023-12-05 11:21 UTC, pr0n00gler commented on docs/neutron/neutron-core-releases.md
> +        - **Technical Enhancements:** Several minor yet impactful technical improvements.
These are no Neutron's Custom Fork changes. It should be moved to **Primate changes** section.

2023-12-05 11:21 UTC, pr0n00gler commented on docs/neutron/neutron-core-releases.md
> +    - Reference to the main [Cosmos SDK v0.47 documentation](https://docs.cosmos.network/v0.47/learn/intro/overview).
Please add

-  `--broadcast-mode` block was removed. You need to query the result for a TX with neutrond q tx <hash> instead;

- the SDK version includes some key store migration for the CLI. Make sure you backup your private keys before testing this! You can not switch back to v0.45;

2023-12-05 11:21 UTC, pr0n00gler commented on docs/neutron/neutron-core-releases.md
> +- **Additional Improvements:** Various other technical modifications and advancements.
Please add:
- legacy REST endpoints for queries and txs are completely removed and only gRPC endpoints must be used now;

And make it bold, cause it's very important.

Also pls add:
- contracts are able to use floating point operations;

2023-12-05 11:24 UTC, pr0n00gler requested changes

2023-12-05 11:24 UTC, pr0n00gler commented on docs/neutron/neutron-core-releases.md
> +This section provides a comprehensive overview of the significant changes and updates in [Neutron version 2](https://github.com/neutron-org/neutron/releases/tag/v2.0.0), focusing on the upgrades to C
> of the significant changes and updates in Neutron version 2
Actually it does not anymore.

It provides info about all the releases of Neutron, not only about v2.

2023-12-05 11:24 UTC, pr0n00gler commented on docs/neutron/neutron-core-releases.md
> +## v2.0.0
Let's make it a link to a Github Release page

2023-12-11 11:05 UTC, pr0n00gler approved these changes
LGTM, waiting for DEX docs merge

2023-12-25 10:07 UTC, merged