NTRN-166 add neutrality docs
neutron-org/neutron-docs pull request #137
Opened 2023-12-05 08:50 UTC by quasisamurai

Here is some questions:

1. There are a lot of _Duality_ mentions here. What's the best alternative of using them everywhere (if needed)? Neutrality? Dex module? any suggestions are welcome.
2. What is the proper link for stuff like curl `http://lcd.duality.xyz/dualitylabs/duality/dex/limit_order_tranche_user`?

2023-12-06 06:24 UTC, jcompagni10 commented
> Here is some questions:
> 
> 1. There are a lot of _Duality_ mentions here. What's the best alternative of using them everywhere (if needed)? Neutrality? Dex module? any suggestions are welcome. I'm gonna rewrite some stuff after receiving an answer

Imho Dex Module or Neutron Dex is fine. But Also curious what Nicholas and Elijah think. 

> 2. What is the proper link for stuff like curl `http://lcd.duality.xyz/dualitylabs/duality/dex/limit_order_tranche_user`?
Not sure, is there a default LCD endpoint that you guys use?

2023-12-06 07:35 UTC, jcompagni10 requested changes

2023-12-06 07:35 UTC, jcompagni10 commented on docs/neutron/modules/dex-module/messages.md
> +Rather than supplying a limit price, limit order take a `TickIndex` as an argument. For maker limit orders this is the tick that the LimitOrderTranche will be placed at. For taker limit order will on
"Rather than supplying a limit price, limit order" 
=> 
"Rather than supplying a limit price, limit orders"

2023-12-06 07:35 UTC, jcompagni10 commented on docs/neutron/modules/dex-module/messages.md
> +Good-til-Cancelled limit orders are hybrid maker and taker limit orders. They will attempt to trade the supplied `AmountIn` at the `TickIndex` or better. However, if they total `AmountIn` cannot be t
"if they total `AmountIn` cannot"

"if the total"...

2023-12-06 07:35 UTC, jcompagni10 commented on docs/neutron/modules/dex-module/messages.md
> +Overview Once a limit order has been filled – either partially or in its entirety, it can be withdrawn at any time. Withdrawing from a limit order credits all available proceeds to the user. Withdraw
Overview should be a subheading

2023-12-06 07:35 UTC, jcompagni10 commented on docs/neutron/modules/dex-module/overview.md
> +## Liquidity Iteration
imho the core concepts should be a different page than the high level duality overview

2023-12-11 12:00 UTC, pr0n00gler requested changes

2023-12-11 12:00 UTC, pr0n00gler commented on docs/neutron/modules/dex-module/messages.md
> +| Creator string (sdk.AccAddress) | Account which controls the limit order and to which any untraded amount is credited |
Please make each field wrapped in \`\` marks

2023-12-11 14:10 UTC, sotnikov-s commented on docs/neutron/modules/dex-module/client.md
> +#### GetUserPositions
we don't have such a query defined for the dex query service: https://github.com/neutron-org/neutron/blob/168815d3703a803f97566f2ddaf0954ac8bda203/proto/neutron/dex/query.proto#L25

2023-12-11 14:10 UTC, sotnikov-s commented on docs/neutron/modules/dex-module/client.md
> +This query retrieves a list of `UserDeposits` items.
let's mention that the returned items are related to the used stated in the query name. also it's not `UserDeposits` but `DepositRecord`
```suggestion
This query retrieves a list of `DepositRecord` items by user address.
```

2023-12-11 14:37 UTC, sotnikov-s commented on docs/neutron/modules/dex-module/client.md
> +This query retrieves a list of `UserLimitOrders` items.
same problem as above with description and struct name:
```suggestion
This query retrieves a list of `LimitOrderTrancheUser` items by user address.
```

2023-12-11 14:37 UTC, sotnikov-s commented on docs/neutron/modules/dex-module/client.md
> +This query retrieves an `InactiveLimitOrderTranche` by index.
the returned type is not **Inactive**LimitOrderTranche, it's just `LimitOrderTranche`, so **inactive** shouldn't be a part of the returned type name

```suggestion
This query retrieves an inactive `LimitOrderTranche` by index.
```

2023-12-11 14:37 UTC, sotnikov-s commented on docs/neutron/modules/dex-module/client.md
> +This query retrieves an `InactiveLimitOrderTranche` by index.
also same suggestion as here for the description of the parameters: https://github.com/neutron-org/neutron-docs/pull/137/files#r1422502915

2023-12-11 14:37 UTC, sotnikov-s commented on docs/neutron/modules/dex-module/client.md
> +This query retrieves a list of `InactiveLimitOrderTranche` items.
same as above about **inactive** being a part of the returned type

```suggestion
This query retrieves a list of inactive `LimitOrderTranche` items.
```

2023-12-11 14:37 UTC, sotnikov-s commented on docs/neutron/modules/dex-module/client.md
> +This query retrieves a `PoolReserve` by index.
```suggestion
This query retrieves a `PoolReserves` by index.
```

2023-12-11 14:37 UTC, sotnikov-s commented on docs/neutron/modules/dex-module/client.md
> +This query retrieves a `PoolReserve` by index.
also same suggestion as here for the description of the parameters: https://github.com/neutron-org/neutron-docs/pull/137/files#r1422502915

2023-12-13 06:17 UTC, sotnikov-s commented on docs/neutron/modules/dex/client.md
> +  // All JIT orders have a goodTilDate of 0 and an exception is made to still still treat these orders as live
> All JIT orders have a goodTilDate of 0

do they? they're [of type time.Time{}](https://github.com/neutron-org/neutron/blob/168815d3703a803f97566f2ddaf0954ac8bda203/x/dex/types/keys.go#L290-L292) which unix timestamp is -62135596800 as far as I understand. please correct me if I'm wrong

2023-12-13 06:19 UTC, sotnikov-s commented on docs/neutron/modules/dex/client.md
> +#### LimitOrderTrancheUserAll
```suggestion
### LimitOrderTrancheUserAll
```

2023-12-13 07:36 UTC, sotnikov-s commented on docs/neutron/modules/dex/client.md
> +  * `MultiHopRoute` : TODO
must be `QueryEstimateMultiHopSwapRequest` here

2023-12-13 07:36 UTC, sotnikov-s commented on docs/neutron/modules/dex/client.md
> +### EstimatePlaceLimitOrder
no description given for the query, please add one

2023-12-13 07:36 UTC, sotnikov-s commented on docs/neutron/modules/dex/client.md
> +  * `id` (uint64): TODO.
just as a reminder (for myself as well): don't forget about a number of TODOs left

2023-12-13 07:36 UTC, sotnikov-s commented on docs/neutron/modules/dex/client.md
> +### PoolRequest
no description given for the query, please add one

2023-12-13 10:11 UTC, quasisamurai commented on docs/neutron/modules/dex-module/client.md
> +This query retrieves a `LimitOrderTranche` by index.
@jcompagni10 wdyt?

2023-12-13 10:13 UTC, quasisamurai commented on docs/neutron/modules/dex/client.md
> +}
it's all just copypasted from [source proto files ](https://github.com/neutron-org/neutron/blob/168815d3703a803f97566f2ddaf0954ac8bda203/proto/neutron/dex/query.proto#L176)

2023-12-13 10:14 UTC, quasisamurai commented on docs/neutron/modules/dex/client.md
> +  * `MultiHopRoute` : TODO
todos will be fixed after figuring out details

2023-12-13 10:18 UTC, quasisamurai commented on docs/neutron/modules/dex/client.md
> +  * `id` (uint64): TODO.
todos will be fixed after figuring out details

2023-12-13 10:26 UTC, quasisamurai commented on docs/neutron/modules/dex-module/overview.md
> +## Liquidity Iteration
don

2023-12-13 10:30 UTC, quasisamurai commented on docs/neutron/modules/dex-module/client.md
> +This query retrieves a `PoolReserve` by index.
I'm not sure where to put this one. how about just adding it to response block @jcompagni10?

2023-12-13 11:38 UTC, sotnikov-s commented on docs/neutron/modules/dex/messages.md
> +  int64 tickIndex = 5;
same in this file re snake case and field names: it's not up to date with the proto files of the module

2023-12-13 11:38 UTC, sotnikov-s commented on docs/neutron/modules/dex/messages.md
> +## Place Limit Order
seems like `Place Limit Order`'s `Overview` and `Order types` sections are duplicated

2023-12-13 11:38 UTC, sotnikov-s commented on docs/neutron/modules/dex/messages.md
> +Overview Once a limit order has been filled – either partially or in its entirety, it can be withdrawn at any time. Withdrawing from a limit order credits all available proceeds to the user. Withdraw
> ### Overview 
> **Overview** Once a limit order...

redundant overview

2023-12-13 11:38 UTC, sotnikov-s commented on docs/neutron/modules/dex/messages.md
> +Overview Once a limit order has been filled – either partially or in its entirety, it can be withdrawn at any time. Withdrawing from a limit order credits all available proceeds to the user. Withdraw
not a native speaker but something seems to me wrong with this sentence

> Withdrawing from a limit order credits all available proceeds to the user

2023-12-13 11:39 UTC, sotnikov-s commented on docs/neutron/modules/dex/client.md
> +  * `MultiHopRoute` : TODO
the request type is invalid. it's `QueryGetPoolReservesRequest` whereas should be `QueryEstimateMultiHopSwapRequest`

2023-12-13 11:41 UTC, sotnikov-s commented on docs/neutron/modules/dex/client.md
> +}
could you please take care of the alignment?

2023-12-13 12:51 UTC, quasisamurai commented on docs/neutron/modules/dex/client.md
> +
this is also a copypaste from source proto

2023-12-14 08:52 UTC, quasisamurai commented on docs/neutron/modules/dex/client.md
> +  * `id` (uint64): TODO.
don

2023-12-14 08:53 UTC, quasisamurai commented on docs/neutron/modules/dex/client.md
> +### PoolRequest
don

2023-12-14 08:53 UTC, quasisamurai commented on docs/neutron/modules/dex/client.md
> +  * `MultiHopRoute` : TODO
don

2023-12-14 08:53 UTC, quasisamurai commented on docs/neutron/modules/dex/client.md
> +}
don

2023-12-14 09:45 UTC, sotnikov-s commented on docs/neutron/modules/dex-module/client.md
> +This query retrieves a `PoolReserve` by index.
why response block if the concern is about the description of request parameters?

2023-12-14 19:54 UTC, jcompagni10 commented on docs/neutron/modules/dex-module/client.md
> +This query retrieves a `LimitOrderTranche` by index.
Effectively this is the tranche key https://github.com/neutron-org/neutron/blob/main/proto/neutron/dex/limit_order_tranche.proto#L11 

Not to be confused with the `tranche_key` https://github.com/neutron-org/neutron/blob/main/proto/neutron/dex/limit_order_tranche.proto#L14

Unfortunately, this is _very_ confusing to have a tranche key and a tranche_key as two totally different things.
This should be renamed in a future release to avoid confusion. 

But I guess I would say "This query retrieves a `LimitOrderTranche` by a tranche's key (pairID + tokenIn + tickIndex + trancheKey).

2023-12-14 20:00 UTC, jcompagni10 commented on docs/neutron/modules/dex-module/client.md
> +This query retrieves a `PoolReserve` by index.
This can be called PoolReservesKey (PairID+TokenIn+TickIndex+Fee)

2023-12-14 20:02 UTC, jcompagni10 commented on docs/neutron/modules/dex/client.md
> +  // GoodTilDate is represented as seconds since  January 1, year 1, 00:00:00.00 UTC
It should be `GoodTilTime` everywhere.  That comment is outdated and should be updated.

2023-12-14 20:08 UTC, jcompagni10 commented on docs/neutron/modules/dex/client.md
> +  // GoodTilDate is represented as seconds since  January 1, year 1, 00:00:00.00 UTC
Per https://github.com/protocolbuffers/protobuf/blob/6ae76fd6ed6507ccab284ed16a430ae42fa64239/src/google/protobuf/timestamp.proto#L53

the comment is correct, but I'm not really sure it needs to be mentioned since it's just an implementation detail.

2023-12-14 20:15 UTC, jcompagni10 commented on docs/neutron/modules/dex/client.md
> +  // All JIT orders have a goodTilDate of 0 and an exception is made to still still treat these orders as live
See above comment. time.Time does not use unix time.

2023-12-15 07:24 UTC, quasisamurai commented on docs/neutron/modules/dex/messages.md
> +Overview Once a limit order has been filled – either partially or in its entirety, it can be withdrawn at any time. Withdrawing from a limit order credits all available proceeds to the user. Withdraw
@jcompagni10

2023-12-15 08:54 UTC, sotnikov-s commented on docs/neutron/modules/dex/client.md
> +### EstimatePlaceLimitOrder
my suggestion here is

> Queries the simulated result of a limit order placement.

2023-12-18 17:37 UTC, jcompagni10 commented on docs/neutron/modules/dex/messages.md
> +Overview Once a limit order has been filled – either partially or in its entirety, it can be withdrawn at any time. Withdrawing from a limit order credits all available proceeds to the user. Withdraw
Looks fine to me

2023-12-19 10:36 UTC, sotnikov-s commented on docs/neutron/modules/dex/client.md
> +This query retrieves an inactive `LimitOrderTranche` by a tranche's key (pairID + tokenIn + tickIndex + trancheKey
```suggestion
This query retrieves an inactive `LimitOrderTranche` by a tranche's key (pairID + tokenIn + tickIndex + trancheKey).
```

2023-12-19 10:36 UTC, sotnikov-s commented on docs/neutron/modules/dex/client.md
> +  // GoodTilDate is represented as seconds since  January 1, year 1, 00:00:00.00 UTC
okay ic. @quasisamurai please update the comment: rm redundant details and fix comment break: https://github.com/neutron-org/neutron/blob/168815d3703a803f97566f2ddaf0954ac8bda203/proto/neutron/dex/limit_order_tranche.proto#L43-L48 is transformed only into a part of the comment: https://github.com/neutron-org/neutron/blob/168815d3703a803f97566f2ddaf0954ac8bda203/x/dex/types/limit_order_tranche.pb.go#L100-L102

2023-12-19 10:38 UTC, sotnikov-s commented on docs/neutron/modules/dex/client.md
> +  // All JIT orders have a goodTilDate of 0 and an exception is made to still still treat these orders as live
it's not `0` then, it's `0001-01-01T00:00:00Z` since time.Time is formatted as RFC 3339 time date

2023-12-19 10:40 UTC, sotnikov-s commented on docs/neutron/modules/dex/client.md
> +  // GoodTilDate is represented as seconds since  January 1, year 1, 00:00:00.00 UTC
I think we need to rephrase the comment here. the field name is `expiration_time` but in the comment we call it `GoodTilDate`, and it's not `seconds since...`, it's an RFC 3339 formatted date time which should be mentioned I think

2023-12-20 06:58 UTC, jcompagni10 approved these changes

2023-12-20 07:42 UTC, jcompagni10 commented on docs/neutron/modules/dex/client.md
> +  // All JIT orders have a goodTilDate of 0 and an exception is made to still still treat these orders as live
"All JIT orders have a goodTilDate of 0 and an exception is made to still still treat these orders as live" 
should be 
 "All JIT orders have a goodTilDate of 0 and an exception is made to still treat these orders as live"

2023-12-20 07:43 UTC, jcompagni10 commented on docs/neutron/modules/dex/client.md
> +  // All JIT orders have a goodTilDate of 0 and an exception is made to still still treat these orders as live
Yes, this is correct. Sorry for the confusion

2023-12-20 11:42 UTC, sotnikov-s approved these changes

2023-12-20 20:49 UTC, jcompagni10 approved these changes

2023-12-22 12:54 UTC, merged