updated icatx docs
neutron-org/neutron-docs pull request #148
Opened 2024-01-24 10:01 UTC by swelf19

2024-01-24 15:18 UTC, pr0n00gler requested changes

2024-01-24 15:18 UTC, pr0n00gler commented on docs/neutron/modules/contract-manager/overview.md
> +1. Make sure that the sudo contract call does not use more gas than allowed by a chain [parameter](#gas-limitation). If the gas limit is exceeded and an out of gas panic occurs inside the sudo call,
```suggestion
1. Make sure that the sudo contract call does not use more gas than allowed by a chain [parameter](#gas-limitation). If the gas limit is exceeded and an out of gas panic occurs inside the sudo call, the wrapper intercepts the panic (only the out of gas panic is intercepted) and converts it to an error.
```

2024-01-24 15:18 UTC, pr0n00gler commented on docs/neutron/modules/interchain-txs/overview.md
> +The interchaintxs module in neutrond configured the following way.
```suggestion
The interchaintxs module in neutrond configured the following way.

```

2024-01-24 15:18 UTC, pr0n00gler commented on docs/neutron/modules/interchain-txs/overview.md
> +wasmd sudo handler wrapped with [sudolimitwrapper](../contract-manager/overview.md#sudolimitwrapper)
```suggestion
Wasmd Sudo handler wrapped with [SudoLimitWrapper](../contract-manager/overview.md#sudolimitwrapper)
```

2024-01-24 15:18 UTC, pr0n00gler commented on docs/neutron/modules/interchain-txs/overview.md
> +`OnAcknowledgementPacket` --> [sudolimitwrapper](../contract-manager/overview.md#sudolimitwrapper) --> `wasmd sudo handler`
```suggestion
`OnAcknowledgementPacket` --> [SudoLimitErapper](../contract-manager/overview.md#sudolimitwrapper) --> `Wasmd Sudo handler`
```

2024-01-24 15:18 UTC, pr0n00gler commented on docs/neutron/modules/interchain-txs/overview.md
> +Using `sudolimitwrapper` has two purposes:
```suggestion
Using `SudoLimitWrapper` has two purposes:
```

2024-01-24 15:18 UTC, pr0n00gler commented on docs/neutron/modules/interchain-txs/overview.md
> +In case of error/expensive tx
```suggestion
In case of error/expensive tx:
```

2024-01-24 15:18 UTC, pr0n00gler commented on docs/neutron/modules/interchain-txs/overview.md
> +Not every interchaintx executes succesfully on a remote network. Some of them fails to execute with errors and then you get ibc acknowledgement with `Error` type. In this case, in order to get additi
> `<binary> q interchain-accounts host packet-events <channel-id> <seq-id>`

Let's say `<binary>` must be replaces with a binary of a remote chain

2024-01-24 15:18 UTC, pr0n00gler commented on docs/neutron/modules/interchain-txs/overview.md
> +For example `gaiad q interchain-accounts host packet-events channel-736 1` is a transaction `fund community pool from neutron unclaimed airdrop` on `cosmoshub-4` chain. Because this command is just a
Is it a real tx on a mainnet? Let's add an rpc here, so a user can copypast the command and that's it

2024-01-24 15:18 UTC, pr0n00gler commented on docs/neutron/modules/interchain-txs/overview.md
> +Unfortunately, to avoid the nondeterminism associated with error test generation, the error text is severely truncated by redact down to the error code without any additional details, before being sa
> the error text is severely truncated by redact down to the error code without any additional details

Please provide a link to the code here

2024-01-27 07:24 UTC, sotnikov-s requested changes

2024-01-27 07:24 UTC, sotnikov-s commented on docs/neutron/modules/interchain-txs/overview.md
> +2. Limit the amount of gas available for sudo handler execution. Out of gas panic will later be captured by `sudolimitwrapper` and converted into an error.
```suggestion
2. Limit the amount of gas available for sudo handler execution. Out of gas panic will later be captured by `SudoLimitWrapper` and converted into an error.
```

2024-01-27 07:24 UTC, sotnikov-s commented on docs/neutron/modules/interchain-txs/overview.md
> +
```suggestion
Not every interchaintx executes succesfully on a remote network. Some of them fail to execute with errors and then you get ibc acknowledgement with `Error` type. In this case, in order to get additional details about the transaction parameters as well as details about the error, you can use the command:

`<binary> q interchain-accounts host packet-events <channel-id> <seq-id>`

Where:

```

added some spaces to make it more readable. otherwise it's all compressed into a single sentence:
<img width="688" alt="image" src="https://github.com/neutron-org/neutron-docs/assets/34917380/156e38d2-e1cd-4897-930a-37542d3ae8e0">

2024-01-27 07:24 UTC, sotnikov-s commented on docs/neutron/modules/interchain-txs/overview.md
> +- `seq-id` - seq of the ibc message received on the host
sounds complicated with a few redundant (IMO) terms introduced and some acronyms that better be elaborated because users need to understand each of the parameters in order to determine the values. can't we go like that?
```suggestion
- `binary` is a binary on the chain you are working with (the remote chain)
- `channel-id` is the ID of the ICA's channel on the remote chain's side
- `seq-id` - sequence ID of the IBC message received on the remove chain
```

might be wrong in something, just a brief suggestion for a better understanding

2024-01-27 07:24 UTC, sotnikov-s commented on docs/neutron/modules/interchain-txs/overview.md
> +- `seq-id` - seq of the ibc message received on the host
also would be useful for a reader to have a hint on how to find these values

2024-01-29 09:09 UTC, sotnikov-s commented on versioned_docs/version-1.0/neutron/modules/interchain-txs/overview.md
> +Where:
```suggestion
Not every interchaintx executes succesfully on a remote network. Some of them fail to execute with errors and then you get ibc acknowledgement with `Error` type. In this case, in order to get additional details about the transaction parameters as well as details about the error, you can use the command:
`<binary> q interchain-accounts host packet-events <channel-id> <seq-id>`
Where:

```

clone of the same suggestion from a comment above

2024-01-29 09:09 UTC, sotnikov-s commented on versioned_docs/version-1.0/neutron/modules/interchain-txs/overview.md
> +- `seq-id` - seq of the ibc message received on the host
same as here https://github.com/neutron-org/neutron-docs/pull/148#discussion_r1468374867

2024-01-29 09:09 UTC, sotnikov-s commented on versioned_docs/version-1.0/neutron/modules/interchain-txs/overview.md
> +For example `gaiad q interchain-accounts host packet-events channel-736 1 --node https://cosmos-rpc.quickapi.com:443` is the transaction `fund community pool from neutron unclaimed airdrop` on `cosmo
same as here https://github.com/neutron-org/neutron-docs/pull/148#discussion_r1468767449

2024-01-29 09:09 UTC, sotnikov-s commented on versioned_docs/version-1.0/neutron/modules/interchain-txs/overview.md
> +Unfortunately, to avoid the nondeterminism associated with error test generation, the error text is severely truncated by [redact down](https://github.com/cosmos/ibc-go/blob/v7.3.1/modules/apps/27-in
```suggestion
Unfortunately, to avoid the nondeterminism associated with error text generation, the error text is severely truncated by [redact down](https://github.com/cosmos/ibc-go/blob/v7.3.1/modules/apps/27-interchain-accounts/host/ibc_module.go#L115) to the error code without any additional details, before being saved to the state on the host interchain account side of the module.
```

clone of the same suggestion from a comment above

2024-02-01 13:22 UTC, swelf19 commented on docs/neutron/modules/interchain-txs/overview.md
> +For example `gaiad q interchain-accounts host packet-events channel-736 1 --node https://cosmos-rpc.quickapi.com:443` is the transaction `fund community pool from neutron unclaimed airdrop` on `cosmo
patch with error emitted as event introduced just 3weeks ago - https://github.com/cosmos/ibc-go/pull/5541. Not sure there any network with patched ibc released, so there is no realworld example. But i've added command output from local chain (gaiad main)

2024-02-03 06:51 UTC, sotnikov-s requested changes
changes are requested for the versioned docs. please reflect them in the current version as well

2024-02-03 06:51 UTC, sotnikov-s commented on versioned_docs/version-1.0/neutron/modules/interchain-txs/overview.md
> +- `seq-id` - sequence ID of the IBC message received on the remove chain
would be very nice to also have info on how to find the the remaining `src-port`, `src-channel-id` and `seq-id`

2024-02-03 06:51 UTC, sotnikov-s commented on versioned_docs/version-1.0/neutron/modules/interchain-txs/overview.md
> +Not every interchaintx executes succesfully on a remote network. Some of them fail to execute with errors and then you get ibc acknowledgement with `Error` type. The error is passed into the caller c
> ... SudoMsg::Error [**varian**](../../../tutorials/cosmwasm_ica.md#ibc-events)

what is varian?

2024-02-03 06:51 UTC, sotnikov-s commented on versioned_docs/version-1.0/neutron/modules/interchain-txs/overview.md
> +Unfortunately, to avoid the nondeterminism associated with error text generation, the error text is severely truncated by [redact down](https://github.com/cosmos/ibc-go/blob/v7.3.1/modules/apps/27-in
let's have a brief explanation of how the returned truncated errors look like (`codespace: wasm, code: 5`) and what to do with these values. I think we can at least follow up the wasm 5 example with attaching a link to all the errors of the module and leaving a comment like "errors and codes are defined by each module in its own way, blah-blah, here's for example how it's made in the wasm module: link" https://github.com/CosmWasm/wasmd/blob/5f444cd9d393513e534cbfa9a0e938295c4e84e1/x/wasm/types/errors.go#L9

2024-02-03 06:51 UTC, sotnikov-s commented on versioned_docs/version-1.0/neutron/modules/interchain-txs/overview.md
> +On earlier versions of ibc-go it's barerly possible to get full text error due to [patch](https://github.com/cosmos/ibc-go/commit/fdbb508c1ca68811206d7175fb9e202c1611a43e)
```suggestion
On earlier versions of ibc-go it's barely possible to get full text error due to [patch](https://github.com/cosmos/ibc-go/commit/fdbb508c1ca68811206d7175fb9e202c1611a43e)
```

2024-02-03 06:51 UTC, sotnikov-s commented on versioned_docs/version-1.0/neutron/modules/interchain-txs/overview.md
> +- `binary` is a binary on the chain you are working with (the remote chain)
```suggestion
- `binary` is a binary of the chain you are working with (the remote chain)
```

2024-02-08 12:07 UTC, sotnikov-s commented on docs/neutron/modules/interchain-txs/overview.md
> +- `seq-id` - sequence ID of the IBC message sent to the remove chain. The seq-id is returned to the contract in the [SubmitTx](./messages.md#response) response
```suggestion
- `seq-id` - sequence ID of the IBC message sent to the remote chain. The seq-id is returned to the contract in the [SubmitTx](./messages.md#response) response
```

2024-02-08 12:07 UTC, sotnikov-s commented on versioned_docs/version-1.0/neutron/modules/interchain-txs/overview.md
> +- `seq-id` - sequence ID of the IBC message sent to the remove chain. The seq-id is returned to the contract in the [SubmitTx](./messages.md#response) response
```suggestion
- `seq-id` - sequence ID of the IBC message sent to the remote chain. The seq-id is returned to the contract in the [SubmitTx](./messages.md#response) response
```

2024-02-08 12:07 UTC, sotnikov-s commented on docs/neutron/modules/interchain-txs/overview.md
> +- `src-port` is the channel you intechain account associated with.
```suggestion
- `src-port` is the port you interchain account is associated with.
```

2024-02-08 12:07 UTC, sotnikov-s commented on versioned_docs/version-1.0/neutron/modules/interchain-txs/overview.md
> +- `src-port` is the channel you intechain account associated with.
```suggestion
- `src-port` is the port you interchain account is associated with.
```

2024-02-08 12:15 UTC, sotnikov-s approved these changes

2024-02-08 18:53 UTC, pr0n00gler approved these changes

2024-02-08 19:57 UTC, merged