Add Neutron forking (rehearsal) documentation
neutron-org/neutron-docs pull request #151
Opened 2024-02-05 20:35 UTC by albertandrejev

This PR contains documentation about how to run Neutron Mainnet Fork for testing purposes.

2024-02-15 11:57 UTC, pr0n00gler requested changes

2024-02-15 11:57 UTC, pr0n00gler commented on docs/other_tools/rehearsal/overview.md
> +Note ‼️: The fork is using neutron image with disabled signature verification, so you can send transactions on behalf of any account. This is done to simplify testing process. Please do not use this
Pls fix formatting of Note part as in the rest of the documentation

2024-02-15 11:57 UTC, pr0n00gler commented on docs/other_tools/rehearsal/overview.md
> +Note: These requirements are based on the standard data volume processed by the Neutron network. More intensive operations or an increase in the blockchain's size may necessitate more robust hardware
Fix here note as well

2024-02-15 11:57 UTC, pr0n00gler commented on docs/other_tools/rehearsal/overview.md
> +- **`./snapshot` Directory:** This directory contains latest snapshot that was downloaded from https://snapshot.neutron.org/ (see `raw` snapshot). If you want to update snapshot simply delete content
```suggestion
- **`./snapshot` Directory:** This directory contains latest snapshot that was downloaded from [Neutron Network Snapshots Service](https://snapshot.neutron.org)(see `raw` snapshot). If you want to update snapshot simply delete contents of the `snapshot` directory and clear appropriate docker volumes.
```

2024-02-16 12:25 UTC, zavgorodnii commented on docs/other_tools/rehearsal/overview.md
> +Note ‼️: The fork is using neutron image with disabled signature verification, so you can send transactions on behalf of any account. This is done to simplify testing process. Please do not use this
Testing scripts **have** a

2024-02-19 09:40 UTC, NeverHappened approved these changes

2024-02-21 09:50 UTC, oldremez approved these changes

2024-02-21 09:52 UTC, ratik approved these changes

2024-02-21 10:01 UTC, pr0n00gler approved these changes

2024-02-23 07:44 UTC, merged