feat: added documentation for privileged subdaos
neutron-org/neutron-docs pull request #152
Opened 2024-02-06 16:51 UTC by zavgorodnii

This PR adds documentation for the privileged SubDAOs subsystem.

2024-02-27 08:08 UTC, NeverHappened approved these changes

2024-03-13 08:43 UTC, sotnikov-s requested changes

2024-03-13 08:43 UTC, sotnikov-s commented on docs/neutron/dao/overview.md
> +<details>
wdyt about moving the whole `Chain management` to a separate page inside the `Neutron DAO` section? I think it deserves a dedicated page. also I find the `Overview` page quite loaded, and here comes another block which is hidden in a drop-down in addition. as a separate page it could be just a block of text without the `<details>` tag

2024-03-13 08:43 UTC, sotnikov-s commented on docs/neutron/dao/overview.md
> +Neither the Neutron DAO, nor the privileged SubDAOs are forced to pass their messages through the cChain manager. If
```suggestion
Neither the Neutron DAO, nor the privileged SubDAOs are forced to pass their messages through the Chain manager. If 
```

2024-03-13 08:43 UTC, sotnikov-s commented on docs/neutron/dao/overview.md
> +The only address that is added to the admin module is the address of the **Chain manager** contract, which implements
let's add some reasoning behind the `Chain manager` contract usage? e.g. say something about time to time network params change necessity, DAO proposals duration and operational load, and intention to unload DAO and let different committees control specific network params

2024-03-13 08:43 UTC, sotnikov-s commented on docs/neutron/dao/overview.md
> +the Chain manager.
if I was a subDAO wanting to change some params, I wouldn't understand a thing out of this description. could you please elaborate and/or provide an example on how to do that?

2024-10-08 23:00 UTC, zavgorodnii commented on docs/neutron/dao/overview.md
> +<details>
I think it looks okay as it is

2024-10-08 23:03 UTC, zavgorodnii commented on docs/neutron/dao/overview.md
> +The only address that is added to the admin module is the address of the **Chain manager** contract, which implements
added slightly below

2024-10-08 23:17 UTC, merged