feat: improved integration tests
neutron-org/neutron-docs pull request #159
Opened 2024-03-04 11:30 UTC by ratik

This one contains of description of new integration tests setup and components

2024-03-06 10:54 UTC, albertandrejev submitted a review, later dismissed

2024-03-07 14:40 UTC, sotnikov-s requested changes

2024-03-07 14:40 UTC, sotnikov-s commented on docs/tutorials/new_integration_tests.md
> +`testcases` folder contains of the tests for the contracts. Each test is a separate file with a set of tests for a contract. Please check the existing tests to understand how to write your own. In th
```suggestion
`testcases` folder contains the tests for the contracts. Each test is a separate file with a set of tests for a contract. Please check the existing tests to understand how to write your own. In the `beforeAll` method you can see the configuration of the networks and the deployment of the contracts.
```

2024-03-07 14:40 UTC, sotnikov-s commented on sidebars.js
> +                'tutorials/new_integration_tests',
@pr0n00gler @swelf19 I think we can simply replace the original `tutorials/integration_tests` page with the new one. The old one suggests to use the quite old-fashioned, overloaded with our specific tests `neutron-integration-tests` repo which I think is more for our own usage. Strangers don't deserve such a suffering. And the new one is quite clean and neat with cool vitest under the hood. What do you think?

2024-03-07 14:40 UTC, sotnikov-s commented on sidebars.js
> +                'tutorials/new_integration_tests',
Another approach here is to keep both pages for a while until we're confident about the new suggested approach (e.g. I didn't run the new workflow, not even sure it works). The `demo-integration-tests` is also poorly documented — don't think it's ready to be used as the only proper documentation for integration tests.

2024-03-07 14:40 UTC, sotnikov-s commented on sidebars.js
> +                'tutorials/new_integration_tests',
1. the header is used as the page name on the sidebar and it's too long for it
2. new_integration_tests is a bit odd name. let's give it another name?
<img width="310" alt="image" src="https://github.com/neutron-org/neutron-docs/assets/34917380/96a2c245-5090-4e53-951e-fd8a1dbcd8cb">

2024-03-07 14:40 UTC, sotnikov-s commented on sidebars.js
> +                'tutorials/new_integration_tests',
another idea is we could add a folder and move the files inside it:

Tutorials
-- Overview
-- Introduction to CosmWasm
-- ...
-- Integration tests
---- Smart contracts (the new one)
---- Legacy (the old one)

2024-03-13 09:29 UTC, ratik commented on sidebars.js
> +                'tutorials/new_integration_tests',
tried to address it. please check if it fits better now

2024-03-15 10:58 UTC, zavgorodnii submitted a review, later dismissed

2024-03-15 12:18 UTC, sotnikov-s approved these changes

2024-04-03 11:20 UTC, pr0n00gler approved these changes

2024-04-03 11:22 UTC, merged