Add Code ID's
neutron-org/neutron-docs pull request #160
Opened 2024-03-04 19:52 UTC by faust403

2024-03-04 21:19 UTC, pr0n00gler submitted a review, later dismissed

2024-03-06 10:52 UTC, albertandrejev approved these changes

2024-03-13 19:26 UTC, NeverHappened requested changes

2024-03-13 19:26 UTC, NeverHappened commented on docs/deployment/mainnet.md
> +| Timelock Module                                       | [neutron1t2t2xj0rkktu3wzutyqazdnpaqg00cam6knmx9uqeawfukqp8fss0hz78j](https://neutron.celat.one/neutron-1/contracts/neutron1t2t2xj0rkktu3wzuty
please merge the main. 
Timelock module was incorrect.
Its moved a little bit to the bottom and also has another address and code id:
see https://neutron.celat.one/neutron-1/contracts/neutron1lvl674duw26psvzux5050du5kfg40kmy5z70t6am8pw6yje2wfjq66lmj2

2024-04-16 09:46 UTC, NeverHappened approved these changes

2024-04-16 09:47 UTC, NeverHappened commented
resolve conflicts please @faust403

2024-05-01 10:00 UTC, pr0n00gler approved these changes

2024-05-07 22:46 UTC, NeverHappened approved these changes

2024-05-27 10:48 UTC, merged