Neutron V3
neutron-org/neutron-docs pull request #163
Opened 2024-03-11 15:41 UTC by pr0n00gler

2024-03-19 15:39 UTC, pr0n00gler commented on docs/neutron/modules/3rdparty/skip/block-sdk/overview.md
> +Skip has built out a number of plug-and-play lanes on the SDK that your protocol can use, including in-protocol MEV recapture and Oracles! Additionally, the Block SDK can be extended to add your own
From my perspective it's too much, yeah.
I don't want to have Skip's docs to be copypasted :(

And i have a link to their docs a bit below

2024-03-26 13:07 UTC, NeverHappened submitted a review, later dismissed

2024-03-27 12:34 UTC, sotnikov-s requested changes

2024-03-27 12:34 UTC, sotnikov-s commented on docs/neutron/neutron-core-releases.md
> +Neutron V3 contains convenient CW bindings (TODO: links/docs) for [Neutron DEX](neutron/modules/dex/overview/overview.md) module which allows to build smart-contract applications in a more
can we resolve the TODO?

2024-04-04 13:24 UTC, pr0n00gler commented on docs/neutron/modules/3rdparty/skip/block-sdk/overview.md
> +* **FrontRunningProtection: `false`** - determines whether front-running and sandwich protection is enabled.
I have the same thoughts about how this actually kinda increases operational cost of docs maintaining, but at the same time it's good to have a place in the docs with the current params, to where i can just copy a link and share it with an interested non-tech person who has troubles with interacting with nodes.

And i don't think this particular params will be changed frequently.

2024-04-04 13:26 UTC, pr0n00gler commented on docs/neutron/modules/3rdparty/skip/block-sdk/overview.md
> +* **FrontRunningProtection: `false`** - determines whether front-running and sandwich protection is enabled.
In general it would be nice to query params for each module directly from node and show them in docs.
I think you can add it into your big docs task if it makes sense

2024-04-04 13:26 UTC, pr0n00gler commented on docs/neutron/neutron-core-releases.md
> +Neutron V3 contains convenient CW bindings (TODO: links/docs) for [Neutron DEX](neutron/modules/dex/overview/overview.md) module which allows to build smart-contract applications in a more
Done

2024-04-04 13:26 UTC, pr0n00gler commented on docs/neutron/modules/3rdparty/skip/block-sdk/overview.md
> +> All auction parameters are accessible though the [/block-sdk/x/auction/v1/params](https://rest-palvus.pion-1.ntrn.tech/swagger/#/Query/Params) HTTP REST endpoint.
Done

2024-04-05 10:05 UTC, sotnikov-s approved these changes

2024-04-10 15:26 UTC, swelf19 commented on docs/neutron/modules/3rdparty/skip/block-sdk/overview.md
> +* **ProposerFee: `25%`** - defines the portion of the winning bid that goes to the block proposer that proposed the block.
in our case that is not exactly true. 25% goes to the account module `cons_redistribute` (https://github.com/neutron-org/neutron/blob/v3.0.2/app/app.go#L634)

2024-04-10 15:26 UTC, swelf19 commented on docs/neutron/build-and-run/neutron-build.md
> +git clone -b v3.0.1 https://github.com/neutron-org/neutron.git
v3.0.2 is the latest one at the moment. Does it worst to change it?

2024-04-10 15:26 UTC, swelf19 commented on docs/tutorials/integration-tests/chain.md
> +* `git clone git@github.com:neutron-org/neutron-query-relayer.git`
sometimes you suggest to use v0.2.0 ICQ version, sometimes not. Maybe we can make docs consistent, same about git protocol, we mix `https` and `ssh`

2024-04-10 15:34 UTC, pr0n00gler commented on docs/neutron/build-and-run/neutron-build.md
> +git clone -b v3.0.1 https://github.com/neutron-org/neutron.git
fixed

2024-04-10 15:34 UTC, pr0n00gler commented on docs/neutron/modules/3rdparty/skip/block-sdk/overview.md
> +* **ProposerFee: `25%`** - defines the portion of the winning bid that goes to the block proposer that proposed the block.
fixed

2024-04-10 15:34 UTC, pr0n00gler commented on docs/tutorials/integration-tests/chain.md
> +* `git clone git@github.com:neutron-org/neutron-query-relayer.git`
I added relayer tag everywhere.
We'll deal with https/ssh later

2024-04-10 15:37 UTC, swelf19 commented on docs/neutron/modules/3rdparty/skip/block-sdk/overview.md
> +* **ProposerFee: `25%`** - defines the portion of the winning bid that goes to the goes to the [account module `cons_redistribute`](https://github.com/neutron-org/neutron/blob/v3.0.2/app/app.go#L634)
> goes to the goes
like a song

2024-04-10 15:39 UTC, pr0n00gler commented on docs/neutron/modules/3rdparty/skip/block-sdk/overview.md
> +* **ProposerFee: `25%`** - defines the portion of the winning bid that goes to the goes to the [account module `cons_redistribute`](https://github.com/neutron-org/neutron/blob/v3.0.2/app/app.go#L634)
lol, fixed

2024-04-10 15:52 UTC, merged