Add gas cost section for dex
neutron-org/neutron-docs pull request #164
Opened 2024-03-12 03:41 UTC by jcompagni10

2024-03-12 15:34 UTC, pr0n00gler requested changes

2024-03-12 15:34 UTC, pr0n00gler commented on docs/neutron/modules/dex/messages.md
> +| New pools                | 21825     | 48076        |
```suggestion
| New pools                | `21825`     | `48076`        |
```

2024-03-12 15:34 UTC, pr0n00gler commented on docs/neutron/modules/dex/messages.md
> +| Adding to existing pools | 19069     | 39100        |
```suggestion
| Adding to existing pools | `19069`     | `39100`        |
```

2024-03-12 15:34 UTC, pr0n00gler commented on docs/neutron/modules/dex/messages.md
> +| 21825     | 32215        |
```suggestion
| `21825`     | `32215`        |
```

2024-03-12 15:34 UTC, pr0n00gler commented on docs/neutron/modules/dex/messages.md
> +| Taker only limit order   | 44213     | 7779         |
```suggestion
| Taker only limit order   | `44213`     | `7779`         |
```

2024-03-12 15:34 UTC, pr0n00gler commented on docs/neutron/modules/dex/messages.md
> +| Maker only GTC           | 31095     | N/A          |
```suggestion
| Maker only GTC           | `31095`     | `N/A`          |
```

2024-03-12 15:34 UTC, pr0n00gler commented on docs/neutron/modules/dex/messages.md
> +| Maker only JIT           | 48095     | N/A          |
```suggestion
| Maker only JIT           | `48095`     | `N/A`          |
```

2024-03-12 15:34 UTC, pr0n00gler commented on docs/neutron/modules/dex/messages.md
> +| Maker only GoodTil       | 49107     | N/A          |
```suggestion
| Maker only GoodTil       | `49107`     | `N/A`          |
```

2024-03-12 15:34 UTC, pr0n00gler commented on docs/neutron/modules/dex/messages.md
> +| 24992     | N/A          |
```suggestion
| `24992`     | `N/A`          |
```

2024-03-12 15:34 UTC, pr0n00gler commented on docs/neutron/modules/dex/messages.md
> +| 25451     | N/A          |
```suggestion
| `25451`     | `N/A`          |
```

2024-03-13 12:05 UTC, pr0n00gler approved these changes

2024-03-15 09:39 UTC, sotnikov-s approved these changes

2024-03-15 09:39 UTC, sotnikov-s commented on docs/neutron/modules/dex/messages.md
> +Below are basic gas estimates for various Dex operations. Depending on the exact state of the dex and the inputs of the message being sent real gas costs can vary substantially. For operations that t
```suggestion
Below are basic gas estimates for various Dex operations. Depending on the exact state of the dex and the inputs of the message being sent real gas costs can vary substantially. For operations that touch multiple ticks the gas cost can be estimated using the formula: $$gasUsed = fixedGasCost + perTickGas*nTicks$$
```

2024-03-18 12:38 UTC, pr0n00gler commented on docs/neutron/modules/dex/messages.md
> +These estimates only consider the gas costs at the message server level and below; application level (ie. AnteHandler) gas costs are not included.
@jcompagni10

2024-03-19 10:54 UTC, pr0n00gler approved these changes

2024-03-19 10:54 UTC, merged

2024-03-19 15:25 UTC, NeverHappened commented on docs/neutron/modules/dex/messages.md
> +Below are basic gas estimates for various Dex operations. Depending on the exact state of the dex and the inputs of the message being sent real gas costs can vary substantially. For operations that t
is this about the looping liquidity pools? I'm trying to understand is the `ticks` word correct in this case. Since we can have a lot of pools in the same tick