feat: add query IDs filter
neutron-org/neutron-docs pull request #171
Opened 2024-04-07 12:13 UTC by dcb9

2024-04-08 13:38 UTC, pr0n00gler submitted a review, later dismissed

2024-04-09 21:13 UTC, joldie777 requested changes

2024-04-09 21:13 UTC, joldie777 commented on docs/relaying/icq-relayer.md
> +- `RELAYER_REGISTRY_QUERY_IDS` — a list of comma-separated query IDs which complements to `RELAYER_REGISTRY_ADDRESSES` to further filter out interchain queries being processed. If empty, no queries w
Could you please replace the dot with a semicolon at the end of the description?
Just to keep the design consistency.

2024-04-10 08:39 UTC, joldie777 approved these changes

2024-05-28 09:38 UTC, pr0n00gler approved these changes

2024-05-28 09:38 UTC, merged