[WIP] Tick, Pools, and PoolReserves updates
neutron-org/neutron-docs pull request #172
Opened 2024-05-15 04:57 UTC by NicholasDotSol

Update documentation in advance of the DEX upgrade.

2024-06-11 16:45 UTC, jcompagni10 approved these changes

2024-06-12 11:48 UTC, pr0n00gler requested changes

2024-06-12 11:48 UTC, pr0n00gler commented on docs/neutron/modules/dex/overview/concepts/swaps.md
> +x
I think this `x` should be removed

2024-06-12 11:48 UTC, pr0n00gler commented on docs/neutron/modules/dex/overview/concepts/swaps.md
>      - In cases where only a portion of the maxAmountIn is used only the used portion of `TokenIn` will be debited from the user's account.
This line has a pretty weird style
<img width="909" alt="Screenshot 2024-06-12 at 2 47 33 PM" src="https://github.com/neutron-org/neutron-docs/assets/6247919/29cb0621-82fe-443d-b873-1e2b2b11f565">
, maybe change to something else?

2024-06-12 19:46 UTC, jcompagni10 commented on docs/neutron/modules/dex/overview/concepts/swaps.md
>      - In cases where only a portion of the maxAmountIn is used only the used portion of `TokenIn` will be debited from the user's account.
Not sure I understand what the issue is here. I did switch to clearer variables and add a missing coma. Let me know if there's something else I am missing @pr0n00gler .

2024-06-13 04:48 UTC, jcompagni10 approved these changes

2024-06-17 13:11 UTC, pr0n00gler approved these changes

2024-06-18 08:00 UTC, NeverHappened requested changes
lgtm, found a few typos and optional suggestions

2024-06-18 14:26 UTC, quasisamurai requested changes

2024-06-18 14:26 UTC, quasisamurai commented on docs/neutron/modules/dex/overview/concepts/amms-and-orderbooks.md
>  Orderbook liquidity providers accrue value through maintaining a bid-ask spread, which entails them offering to sell assets slightly above the current current price and buy them slightly below the cu
```suggestion
Orderbook liquidity providers accrue value through maintaining a bid-ask spread, which entails them offering to sell assets slightly above the current price and buy them slightly below the current price. It turns out that these two mechanism are actually very similar in that they describe the difference in prices between the best sell and buy prices.
```

2024-06-18 14:26 UTC, quasisamurai commented on docs/neutron/modules/dex/overview/concepts/liquidity-iteration.md
> +When swapping through liquidity via a Multi-Hop Swap or a Taker Limit Order we iterate through the available `TickLiquidity` to fill the swap order. Liquidity is always iterated through in order of b
```suggestion
When swapping through liquidity via a Multi-Hop Swap or a Taker Limit Order, we iterate through the available `TickLiquidity` to fill the swap order. Liquidity is always iterated through in order of best to worst price (from the taker's perspective.) For each swap, we completely exhaust the available reserves before moving on to the next tick. For `TickLiquidity` instances at the same `TickIndex` they are iterated through in a deterministic order as follows:
```

2024-06-18 14:26 UTC, quasisamurai commented on docs/neutron/modules/dex/overview/concepts/liquidity-iteration.md
> +This tick offers `ATOM` at a price of $0.123$ `ATOM` per `USDC` and is of type `PoolReserve`. Any USDC alice pays for this swap will be placed in the corresponding poolReserves of the Pool (USDC @ Ti
```suggestion
This tick offers `ATOM` at a price of $0.123$ `ATOM` per `USDC` and is of type `PoolReserve`. Any USDC Alice pays for this swap will be placed in the corresponding poolReserves of the Pool (USDC @ Tick $$-20795$$ .) Alice swaps the remainder of her `USDC` here, resulting in an additional $3.5$ `ATOM`:
```

2024-06-19 15:52 UTC, NicholasDotSol commented on docs/neutron/modules/dex/messages.md
> +  uint64 max_JITs_per_block = 3;
Max_JITsPerBlock is correct

2024-06-19 15:58 UTC, NicholasDotSol commented on docs/neutron/modules/dex/messages.md
> +When depositing into an LP position (`PoolReserves`) a user specifies amounts of `TokenA` and `TokenB` as well as a `TickIndexAToB` and a fee. The liquidity is added to the reserves for the respectiv
TokenA and tokenB are a user convenience, the DEX internally uses token0 and token1. When we say the user doesn't need to care about the canonical toke0 and token1 we mean the user only cares about providing the correct tokenA and token B. I'll try to clarify this in a different way

2024-06-19 15:58 UTC, NicholasDotSol commented on docs/neutron/modules/dex/messages.md
>  **NOTE**: Most pools will only have Token1 OR Token0, so most deposits will only be providing one tokens to one side of the pool.
DEX deals with token0 and token1 internally

2024-06-19 16:27 UTC, NicholasDotSol commented on docs/neutron/modules/dex/messages.md
> +By default the `autoswap` option is enabled, which allows users to deposit their full deposit amount.  Autoswap provides a mechanism for users to deposit the entirety of their specified deposit amoun
will add clarification

2024-06-19 18:56 UTC, NicholasDotSol commented on docs/neutron/modules/dex/overview/concepts/tick-liquidity.md
> +`TickLiquidity` structs are used to store liquidity within the Dex. Each tick has a specific price and holds liquidity for a single token. `TickLiquidity` come in two general types --`PoolReserves` f
not entirely sure what you mean, attempted a fix though

2024-06-19 22:57 UTC, jcompagni10 commented on docs/neutron/modules/dex/messages.md
> +  uint64 max_JITs_per_block = 3;
It was changed https://github.com/neutron-org/neutron/blob/28b1d2ce968aaf1866e92d5286487f079eba3370/x/dex/types/params.pb.go#L31

2024-06-21 11:03 UTC, NeverHappened approved these changes

2024-06-26 11:35 UTC, pr0n00gler approved these changes

2024-06-26 11:35 UTC, merged