NTRN-303 add basic slinky bindings docs
neutron-org/neutron-docs pull request #176
Opened 2024-05-30 17:22 UTC by quasisamurai

2024-05-31 09:45 UTC, pr0n00gler requested changes

2024-05-31 09:45 UTC, pr0n00gler commented on docs/neutron/modules/3rdparty/skip/slinky/overview.md
> +For example usage of these queries in contract, check our related [dev-contract](https://github.com/neutron-org/neutron-dev-contracts/blob/727aa94dff53373e34226d31d5bdcfc66e3a1aaf/contracts/oracle/sr
Let's do not refer to dev-contract in the docs.

We usually refer to simple and easily readable contracts in neutron-sdk repo

2024-05-31 09:45 UTC, pr0n00gler commented on docs/neutron/modules/3rdparty/skip/slinky/overview.md
> +We have integrated the [Slinky](https://skip-protocol-docs.netlify.app/slinky/overview) modules (Oracle & MarketMap) into the Neutron and added WASM bindings to facilitate their usage. This integrati
Weird link, why not `https://docs.skip.money/slinky/overview`?

2024-05-31 09:45 UTC, pr0n00gler commented on docs/neutron/modules/3rdparty/skip/slinky/overview.md
> +For example usage of these queries in contract, check our related [dev-contract](https://github.com/neutron-org/neutron-dev-contracts/blob/feat/sdk-50/contracts/marketmap/src/contract.rs#L52)
The same about dev-contracts

2024-06-06 14:49 UTC, sotnikov-s requested changes
please attach a link to the task and add some description to the PR

2024-07-01 14:43 UTC, sotnikov-s requested changes

2024-07-03 09:57 UTC, sotnikov-s commented on sidebars.js
> +                                    label: "Cosmos Hub",
and the bindings pages are not included in the sidebars.js

2024-07-03 09:57 UTC, sotnikov-s commented on docs/neutron/modules/3rdparty/skip/slinky/bindings/messages.md
> +   ```
there is a number of unformatted snippets. please apply formatting:

<img width="639" alt="image" src="https://github.com/neutron-org/neutron-docs/assets/34917380/ea2dada8-ad6c-4529-a372-2bef4db096a6">

2024-07-03 09:58 UTC, sotnikov-s commented on docs/neutron/modules/3rdparty/skip/slinky/bindings/messages.md
> +resp:
```suggestion
Response:
```

2024-09-02 10:45 UTC, closed without merging