feat/add-icq-relayer-shutdown-description
neutron-org/neutron-docs pull request #27
Opened 2022-10-25 14:09 UTC by sotnikov-s

inspired during work on https://github.com/neutron-org/neutron-query-relayer/pull/50

2022-10-31 17:19 UTC, foxpy submitted a review, later dismissed

2022-11-03 10:49 UTC, foxpy requested changes

2022-11-03 10:49 UTC, foxpy commented on docs/relaying/icq-relayer.md
> +During the execution the Neutron ICQ Relayer receives events from Neutron, reads remote chain's state, and modifies its own state and the Neutron' one. In order to reach a reliable and consistent flo
```suggestion
During the execution the Neutron ICQ Relayer receives events from Neutron, reads remote chain's state, and modifies its own state and the Neutron' one. In order to reach a reliable and consistent flow the Relayer is designed the way it finishes initialised interactions with its local storage when `SIGINT` or `SIGTERM` signal is received. It usually takes a fraction of a second.
```

2022-11-03 10:52 UTC, sotnikov-s commented on docs/relaying/icq-relayer.md
> +During the execution the Neutron ICQ Relayer receives events from Neutron, reads remote chain's state, and modifies its own state and the Neutron' one. In order to reach a reliable and consistent flo
what's wrong with the way I wrote it? :)

2022-11-03 12:30 UTC, NeverHappened commented on docs/relaying/icq-relayer.md
> +During the execution the Neutron ICQ Relayer receives events from Neutron, reads remote chain's state, and modifies its own state and the Neutron' one. In order to reach a reliable and consistent flo
I would just change to `is designed **to finish** initialised ....`

2022-11-03 22:57 UTC, foxpy commented on docs/relaying/icq-relayer.md
> +During the execution the Neutron ICQ Relayer receives events from Neutron, reads remote chain's state, and modifies its own state and the Neutron' one. In order to reach a reliable and consistent flo
> what's wrong with the way I wrote it? :)

Just suggesting you a little cleaner way to write it.

Actually, we need someone who is at least C1 in English (I guess almost everyone in our team is B1-B2) to proof read our documentation and point out how to write it cleaner.

You are free to close this thread yourself, and, if you do so, I will approve this PR.

2022-12-05 09:41 UTC, foxpy approved these changes
Approving it since it is stalled…

2022-12-05 11:59 UTC, merged