feat: ignore sudo error on ACK
neutron-org/neutron-docs pull request #30
Opened 2022-10-31 20:16 UTC by albertandrejev

In this PR documentation for issue #2 from the audit report will be added.

In case of Sudo handler error state of the contract will be reverted and ACK as well as acknowledgement identifiers will be stored in the store. New module to get list of failed acks ids with contracts addresses will be added. Module name will be `contractmanager`

1. [Module PR](https://github.com/neutron-org/neutron/pull/84)

More info: https://p2pvalidator.atlassian.net/browse/NTRN-253

2022-11-01 08:27 UTC, foxpy commented on docs/neutron-core/contract-manager/client.md
> +  ```shell
Hmmm, maybe try using YAML syntax? it may actually color output better, what do you think?

2022-11-01 08:29 UTC, foxpy requested changes

2022-11-01 08:29 UTC, foxpy commented on docs/neutron-core/contract-manager/client.md
> +Returns list of all failures for specific contract address.
But contract address is optional here. If it is optional, then how does it differ to call `all-failures` and `contract-failures`? If there is no difference, I suggest removing `all-failures` alltogether. If there is some difference, it should be pointed out in the doc.

2022-11-01 11:15 UTC, albertandrejev commented on docs/neutron-core/contract-manager/client.md
> +  ```shell
let me try

2022-11-01 12:47 UTC, albertandrejev commented on docs/neutron-core/contract-manager/client.md
> +  ```shell
done

2022-11-01 16:30 UTC, oopcode commented on docs/neutron-core/contract-manager/overview.md
> +Due to the fact that contracts are allowed to make calls to the IBC, as well as process all received data, a problem arises in which a malicious contract can make a call to the IBC and, during the re
amazing, clear as day

2022-11-01 16:32 UTC, oopcode commented on docs/neutron-core/contract-manager/overview.md
> +In this implementation, the second approach was used.
Please add that given the fact that Neutron makes the contract pay for all packets (using ibc fees), it's hard to spam / overflow neutron with failure records

2022-11-02 10:56 UTC, oopcode approved these changes

2022-11-02 10:59 UTC, foxpy approved these changes

2022-11-02 11:00 UTC, merged