feat/add-tx-submission-height-explanation
neutron-org/neutron-docs pull request #32
Opened 2022-11-01 15:19 UTC by sotnikov-s

2022-11-02 09:13 UTC, foxpy requested changes

2022-11-02 09:13 UTC, foxpy commented on docs/relaying/icq-relayer.md
> +The Relayer uses the `BroadcastTxSync` messages broadcast type to maintain balance between performance and submission detalisation, but this means that the submission result is not waited for. And he
What I don't like here is youw roding around "submission detalisation". I would rather write it like "performance and flexibility" or somethig like that. The word "detalisation" is really odd in this context.

2022-11-02 09:13 UTC, foxpy commented on docs/relaying/icq-relayer.md
> +The Relayer uses the `BroadcastTxSync` messages broadcast type to maintain balance between performance and submission detalisation, but this means that the submission result is not waited for. And he
In "To achieve both submission speed and only one submission handling" I suggest you to replace "one" with "single".

2022-11-02 11:27 UTC, foxpy approved these changes

2022-11-03 12:27 UTC, NeverHappened approved these changes
Looks good!

2022-11-07 12:48 UTC, merged