Feat: add tokenomics documentation #NTRN-333 #NTRN-334 #NTRN-335
neutron-org/neutron-docs pull request #47
Opened 2023-01-23 15:49 UTC by foxpy

2023-01-24 09:04 UTC, pr0n00gler requested changes
There are no links to the contracts in the repo. Would be nice if:
* each message/query has links to the corresponding handler in the contracts code;
* overview of each contract has links to the corresponding logic in the code (especially treasury and distribution contract overviews);
* some links to the pausing logic in the code.

2023-01-24 11:41 UTC, NeverHappened commented on docs/neutron/tokenomics/treasury/messages.md
> +# Messages
Yeah, and to be the same everywhere lets use following structure:
# Messages
## Instantiate
## Messages (?)
### Message1
### Message2

2023-01-24 11:56 UTC, foxpy commented on docs/neutron/tokenomics/treasury/messages.md
> +# Messages
I would replace "Messages (?)" with ExecuteMsg

2023-01-24 14:16 UTC, foxpy commented on docs/neutron/tokenomics/reserve/messages.md
> +
And now we have both code comments in enum declaration and standalone articles per each message. Please pick one, having both at the same time doesn't look great.

2023-01-24 15:39 UTC, NeverHappened commented on docs/neutron/tokenomics/reserve/messages.md
> +
I don't know what to pick. I like code ones more, but you cannot link them from other places

2023-01-24 18:32 UTC, pr0n00gler commented on docs/neutron/tokenomics/reserve/messages.md
> +
Why can't we have both? The difference is standalone articles should be more informative

2023-01-31 11:48 UTC, albertandrejev commented on docs/neutron/tokenomics/treasury/overview.md
> +Initialization message contains Main DAO and Security DAO address.
what docs?

2023-01-31 12:23 UTC, albertandrejev commented
> There are no links to the contracts in the repo. Would be nice if:

> each message/query has links to the corresponding handler in the contracts code;
> overview of each contract has links to the corresponding logic in the code (especially treasury and distribution contract overviews);
> some links to the pausing logic in the code.

It is hard to have links to the code because these links becomes outdated very quickly. Maybe we can add links to the contracts itself or to the file containing required code (but that doesn't fix the problem completely.)

2023-02-01 10:59 UTC, pr0n00gler commented on docs/neutron/tokenomics/treasury/messages.md
> +Pause contract for `duration` amount of blocks. Permissioned can be executed only by Main DAO or the Security DAO. If contract is in paused state it disables `exectue` method processing for any messa
```suggestion
Pause contract for `duration` amount of blocks. Permissioned can be executed only by Main DAO or the Security DAO. If contract is in paused state it disables `execute` method processing for any message except `Pause` and `Unpause`.
```

2023-02-01 11:35 UTC, merged