add docs for credits contract #ntrn-365
neutron-org/neutron-docs pull request #48
Opened 2023-02-20 09:01 UTC by NeverHappened

2023-03-01 16:49 UTC, oopcode requested changes
Did you try running the docs server locally? You didn't add this file to sidebar.js, so I'm not sure it's possible to actually see it in the UI.

2023-03-02 08:45 UTC, sotnikov-s requested changes

2023-03-02 08:45 UTC, sotnikov-s commented on docs/neutron/token-generation-event/credits.md
> +- lockdrop can execute `BurnFrom(owner, amount)` to send `amount` of NTRN's to `owner` (This action skips vesting as a reward for lockdrop participation).
you say above that

**Users** that have CUNTRN's on balance, **have two ways** of getting NTRN's

but in the second way of getting NTRNs you describe actions from the lockdrop's contract point of view. could you please elaborate the second way so it contains the whole flow from the user's point of view?

2023-03-02 11:44 UTC, oopcode requested changes

2023-03-02 11:44 UTC, oopcode commented on docs/neutron/token-generation-event/credits.md
> +- mint mints to the airdrop address only and requires NTRN's sent along
```suggestion
- `Mint` mints to the airdrop address only and requires NTRN's sent along
```

2023-03-02 11:44 UTC, oopcode commented on docs/neutron/token-generation-event/credits.md
> +- specific permissions for some operations
what operations, what permissions?

2023-03-02 11:44 UTC, oopcode commented on docs/neutron/token-generation-event/credits.md
> +- burn/burn_from/withdraw not only burns tokens, but also transfers NTRN's to addresses in 1:1 proportion to burned cuntrns
```suggestion
- `Burn`/`BurnFrom`/`Withdraw` not only burns tokens, but also transfers NTRN's to addresses in 1:1 proportion to burned ucNTRNs
```

2023-03-02 11:44 UTC, oopcode commented on docs/neutron/token-generation-event/credits.md
> +- withdraw has a vesting mechanism attached
```suggestion
- `Withdraw` has a vesting mechanism attached (tokens are linearly vested for a given amount of time)
```

2023-03-02 11:44 UTC, oopcode commented on docs/neutron/token-generation-event/credits.md
> +Contract instantiated by DAO and holds airdrop and lockdrop contract addresses for permission purposes.
```suggestion
The contract is owned by the Neutron DAO and needs to know airdrop and lockdrop contract addresses for permission purposes.
```

2023-03-02 11:44 UTC, oopcode commented on docs/neutron/token-generation-event/credits.md
> +1. Airdrop calculates amount of needed airdrops for users and uses `Transfer(recipient, amount)` together with `AddVesting(address, amount, start_time, duration)` to transfer funds and set vesting sc
```suggestion
1. Airdrop calculates the amount of airdrops for users and uses `Transfer(recipient, amount)` together with `AddVesting(address, amount, start_time, duration)` to transfer funds and set vesting schedule (Always a linear vesting with 0 CLIFF time).
```

2023-03-02 15:06 UTC, NeverHappened commented
added to sidebar, fixed token names and more!

2023-03-03 07:40 UTC, sotnikov-s commented on sidebars.js
> +                    label: 'TGE',
let's make the label as disclosed abbreviation? our docs are public whereas TGE may be unclear for a reader. the sidebar width allows it
<img width="290" alt="image" src="https://user-images.githubusercontent.com/34917380/222660478-43350e7b-d074-4a0d-a1c7-d068344e1553.png">

2023-03-03 07:40 UTC, sotnikov-s commented on docs/neutron/token-generation-event/credits.md
> +Basically it's a modified for our purposes CW20 token that holds balances for addresses and can transfer them to others.
> that holds balances

this part seems to be unnecessary because this is the way how basic cw20 tokens work — they are simply a mapping address->balances. given the fact that in the beginning of the sentence you highlight that it's a modified version, I think it's reasonable to focus on modifications we've made, otherwise it's confusing

> can transfer them to others

looks like contract itself is capable of transferring tokens to others transfer. maybe we better mention here that the token transfer is only available for the airdrop contract?

2023-03-03 07:40 UTC, sotnikov-s commented on docs/neutron/token-generation-event/credits.md
> +- Only `Withdraw` is permissionless;
actually I've just noticed that Mint is permissionless as well:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/34917380/222657254-8d84de00-b2f4-4328-91f0-cffe3660315e.png">

please fix it in docs and in credits contract (e.g. in Murad's PR)

2023-03-03 07:40 UTC, sotnikov-s commented on docs/neutron/token-generation-event/credits.md
> +DAO executes `Mint()` with untrn's to mint cNTRN funds in 1:1 proportion and assigns newly minted cNTRN funds to the airdrop address.
> DAO executes `Mint()` with untrn's to mint cNTRN

DAO executes `Mint()` with untrn**s sent along** to mint cNTRN

2023-03-03 07:40 UTC, sotnikov-s commented on docs/neutron/token-generation-event/credits.md
> +- users can execute `Withdraw()` to burn cNTRN's and get untrn's according to the vesting schedule. They can look into how much they can withdraw now using `WithdrawableAmount(address)` query. `Withd
`untrn's` is an incorrect form, should be just `untrn` singular. here and in a couple of other places in the doc. the same about `cNTRN's`. haven't seen ETH or BTC mentions like `send us your ETH's` or something, it's always singular

2023-03-03 08:21 UTC, NeverHappened commented on docs/neutron/token-generation-event/credits.md
> +- Only `Withdraw` is permissionless;
Its not permissionless - it has checks in execute_mint, that checks that tokeninfo.minter is the same as sender

2023-03-03 08:22 UTC, sotnikov-s commented on docs/neutron/token-generation-event/credits.md
> +- Only `Withdraw` is permissionless;
oh, interesting!

2023-03-07 13:25 UTC, merged