NTRN-357 Oracle docs
neutron-org/neutron-docs pull request #49
Opened 2023-02-21 07:41 UTC by quasisamurai

2023-02-26 19:12 UTC, foxpy reviewed
Is `docs/neutron/token-generation-event/overview.md` supposed to be empty?

2023-02-26 19:12 UTC, foxpy commented on docs/neutron/token-generation-event/oracle/queries.md
> +    TWAPAtHeight {}, // returns `AssetInfo, Deciimal256`
What is a "given" height? Querier doesn't provide any height in this context, so a height cannot be "given". I guess you wanted to write something like "last height for which a TWAP is recorded"? Or am I wrong?

2023-03-01 16:50 UTC, oopcode requested changes
Did you try running the docs server locally? You didn't add this file to sidebar.js, so I'm not sure it's possible to actually see it in the UI.

2023-03-02 11:33 UTC, oopcode requested changes

2023-03-02 11:33 UTC, oopcode commented on docs/neutron/token-generation-event/oracle/queries.md
> +This contract accepts these query msgs:
```suggestion
This contract accepts the following query msgs:
```

2023-03-02 11:33 UTC, oopcode commented on docs/neutron/token-generation-event/oracle/overview.md
> +## Overviewew
```suggestion
## Overview
```

2023-03-02 11:33 UTC, oopcode commented on docs/neutron/token-generation-event/oracle/overview.md
> +# Oracle
I don't see a section that describes the diff from the original twap contract, please add it

2023-03-07 14:14 UTC, quasisamurai commented on docs/neutron/token-generation-event/oracle/queries.md
> +    TWAPAtHeight {}, // returns `AssetInfo, Deciimal256`
1. It is. It is placeholder for now. 
2. TWAPAtHeight here missing some params, there are actually 2 of them

2023-03-09 10:04 UTC, oopcode approved these changes

2023-03-09 10:04 UTC, merged