chore: polish
neutron-org/neutron-docs pull request #60
Opened 2023-03-29 14:55 UTC by sotnikov-s

- polish ICQ relayer's configuration section;
- fix and elaborate section about query deposit and query removal;
- update RemoveInterchainQuery message description.

2023-04-03 05:25 UTC, foxpy requested changes

2023-04-03 05:25 UTC, foxpy commented on docs/neutron/interchain-queries/overview.md
> +The `RemoveInterchainQuery` possesses of the following execution permissions:
"possesses of"? That's some funky language. Please use something simple, like "has following permissions" or "supports following permissions", depending on what you meant in a first place.

2023-04-03 16:22 UTC, foxpy approved these changes

2023-04-10 11:33 UTC, oopcode approved these changes

2023-04-10 11:33 UTC, merged