Add CosmWasm contracts tutorials
neutron-org/neutron-docs pull request #93
Opened 2023-06-17 10:45 UTC by udit-gulati

Following tutorial pages have been added:

1. **The counter contract**: Explains basics of CosmWasm contract using counter example.
2. **Deploy your first contract**: Walkthough of scaffolding contracts repo, deploying, testing and interacting with the contracts, running local network and generating contract schema.

2023-06-26 14:34 UTC, sotnikov-s requested changes
thanks a lot for your hard work! that's a great starting point for neutron's cosmwasm tutorial documentation. please consider the comments I've left. I also want to add some additional info and change sidebars organisation later when you've managed my change requests. my plans are:
- create a dedicated folder for this kind of tutorial;
- create an overview page;
- maybe add some info about the wasm module;
- add a page with links to external docs and guides e.g. best practices, useful libraries, etc.

do you mind if I then do it right here in your PR?

2023-06-26 14:34 UTC, sotnikov-s commented on docs/tutorials/first_contract.md
> +      docker_image: "uditgulati0/neutron-node",
please replace this one with the neutron official docker image that can be creates as follows:

1. clone neutron repo https://github.com/neutron-org/neutron
2. run `make build-docker-image` from the repo root directory
3. use `neutron-node` image here

2023-06-26 14:34 UTC, sotnikov-s commented on docs/tutorials/first_contract.md
> +npx wasmkit node-info --network localnet`
redundant trailing ` which breaks markdown

2023-07-01 10:32 UTC, foxpy commented on docs/tutorials/first_contract.md
> +      docker_image: "uditgulati0/neutron-node",
That's actually a problem about our Docker image. Instead of simply pulling from dockerhub, people have to build it theirselves. People really don't want to do that :p

2023-07-03 07:52 UTC, sotnikov-s commented on docs/tutorials/first_contract.md
> +      docker_image: "uditgulati0/neutron-node",
I agree that we need to address this issue, but at this point it's more reasonable to make people build it by their own hands than to have a link to an unofficial image in our official docs. meaning no offence to the contributors but I wouldn't like to check that the image is not malicious, would you?

2023-07-06 10:22 UTC, udit-gulati commented on docs/tutorials/counter_contract.md
> +## Contract dependencies
Agreed, I think it's better to remove it for now and maybe add something else in it's place if contracts devs have hard time understaning the structure of the toml file. Or even a dedicated page to elaborate upon how `Cargo.toml` file works and some sample use cases.

2023-07-06 10:23 UTC, udit-gulati commented on docs/tutorials/counter_contract.md
> +pub const CONSTANTS: Item<Constants> = Item::new("constants");
Yes, fixed :)

2023-07-06 10:48 UTC, udit-gulati commented on docs/tutorials/counter_contract.md
> +`Addr` refers to a human-readable Neutron address prefixed with neutron, e.g. `neutron1retp3n0xl0sucqmg4qdk64h7kfflc032xg8na0`.
Yeah, `Addr` is more suitable for `owner` than `String`.

2023-07-06 11:53 UTC, udit-gulati commented on docs/tutorials/counter_contract.md
> +The logic for `query()` is similar to that of `execute()`; however, since `query()` is called without the end-user making a transaction, the `env` argument is omitted as no information is necessary.
Sure

2023-07-06 16:45 UTC, udit-gulati commented on docs/tutorials/first_contract.md
> +      docker_image: "uditgulati0/neutron-node",
We can definitely remove the dockerhub image from default config. The idea of doing it this way was to have a working flow that requires minimal effort from the contract dev and does not depend on local go environment. 

If there is dockerhub image for official neutron release, we can use that (other teams such as SecretNetwork do push their built images as then make a new release).

Or building locally like @sotnikov-s suggested is fine too.

2023-07-06 16:53 UTC, udit-gulati commented
Hi @sotnikov-s, thanks for the detailed review.

> thanks a lot for your hard work! that's a great starting point for neutron's cosmwasm tutorial documentation. please consider the comments I've left. I also want to add some additional info and change sidebars organisation later when you've managed my change requests. my plans are:
> 
> * create a dedicated folder for this kind of tutorial;
> * create an overview page;
> * maybe add some info about the wasm module;
> * add a page with links to external docs and guides e.g. best practices, useful libraries, etc.
> 
> do you mind if I then do it right here in your PR?

Sure, please do.

Additionally, we can even add some video tutorials embedded into the docs which could be either the existing ones or can create neutron specific ones. Let me know what you think of this.

2023-07-13 14:46 UTC, sotnikov-s commented
> Hi @sotnikov-s, thanks for the detailed review.
> 
> > thanks a lot for your hard work! that's a great starting point for neutron's cosmwasm tutorial documentation. please consider the comments I've left. I also want to add some additional info and change sidebars organisation later when you've managed my change requests. my plans are:
> > 
> > * create a dedicated folder for this kind of tutorial;
> > * create an overview page;
> > * maybe add some info about the wasm module;
> > * add a page with links to external docs and guides e.g. best practices, useful libraries, etc.
> > 
> > do you mind if I then do it right here in your PR?
> 
> Sure, please do.
> 
> Additionally, we can even add some video tutorials embedded into the docs which could be either the existing ones or can create neutron specific ones. Let me know what you think of this.

thank you a lot for addressing the comments of mine. I'll implement and push my part in a few days

2023-08-11 09:34 UTC, udit-gulati commented
Hi @sotnikov-s, got any update for me on this PR?

2023-08-11 09:59 UTC, sotnikov-s commented
> Hi @sotnikov-s, got any update for me on this PR?

Hello dear friend. I'm terribly sorry but not yet. I was on a two weeks vacation and got back to work only on this week. Will do my best to finish this PR next week

2023-08-22 05:43 UTC, udit-gulati commented
@sotnikov-s @foxpy are we good to merge this PR or need additional work? If good to merge, then I resolve the conflicts.

2023-08-22 07:08 UTC, sotnikov-s commented
> @sotnikov-s @foxpy are we good to merge this PR or need additional work? If good to merge, then I resolve the conflicts.

hi hi. you've mentioned in DM that you want to make a couple of changes re my comments. I think it would make sense to make it done and then merge. what do you think? I could finish my way through the wasmkit usage in the meanwhile

2023-08-22 11:30 UTC, foxpy requested changes
Thank you for your work! I will be happy to see it included in our docs, however, I have multiple concerns to be accounted for:

2023-08-22 11:30 UTC, foxpy commented on docs/tutorials/cosmwasm_wasmkit.md
> +```
I personally don't like suggesting people to run `curl x.y.z | shell`, so I would rather point them to navigate to https://www.rust-lang.org/tools/install and install Rust themselves. Yeah, it makes this process a little bit longer, but at least I wouldn't feel uncomfortable of suggesting people to execute curled scripts from the Internet.

2023-08-22 11:30 UTC, foxpy commented on docs/tutorials/cosmwasm_wasmkit.md
> +```
It still needs yarn to work, so, what's the point of providing this particular instruction? I would rather call `yarn add` myself.

2023-08-22 11:30 UTC, foxpy commented on docs/tutorials/cosmwasm_wasmkit.md
> +The RPC URL for this localnetwork will be `http://localhost:26657` and REST URL will be `http://localhost:1317`. This can be verfiied by doing:
```suggestion
The RPC URL for this localnetwork will be `http://localhost:26657` and REST URL will be `http://localhost:1317`. This can be verified by doing:
```

2023-08-22 14:34 UTC, udit-gulati commented on docs/tutorials/cosmwasm_wasmkit.md
> +```
I think having both in the doc would be better.

2023-08-22 14:38 UTC, udit-gulati commented on docs/tutorials/cosmwasm_wasmkit.md
> +```
This could be useful when building the dev (nightly) branch which is not published to npm yet, or building wasmkit from source to maybe contribute.

2023-08-22 14:41 UTC, udit-gulati commented on docs/tutorials/introduction_to_cosmwasm.md
> +A smart contract can be considered an instance of a singleton object whose internal state is persisted on the blockchain. Users can trigger state changes by sending the smart contract JSON messages,
That's a fair point, I think removing it from here is better cause this is smart contract introduction and expalining the messages here would make it complex for an introduction.

2023-08-22 14:59 UTC, udit-gulati commented
Hi @foxpy, thanks for the detailed review and apologies for so many typos. I've resolved most of the suggestions and commented on the remaining ones. Please have a look.

2023-08-22 15:00 UTC, udit-gulati commented on docs/tutorials/introduction_to_cosmwasm.md
> +On the Neutron blockchain, the uploading of a contract's code and the instantiation of a contract are regarded as separate events, unlike on Ethereum. This is to allow a small set of vetted contract
Updated to specify that Neutron uses CosmWasm as smart contract layer and CosmWasm design has deploy, init separation.

2023-08-23 09:09 UTC, foxpy commented on docs/tutorials/cosmwasm_wasmkit.md
> +```
It is just super uncomfortable for me. I think I will just let @sotnikov-s decide.

2023-08-23 09:17 UTC, foxpy commented on docs/tutorials/introduction_to_cosmwasm.md
> +In our sample counter contract, we will implement one instantiate, one query, and two execute methods.
Well, let's hope the new version will be less confusing :)

2023-08-23 09:20 UTC, foxpy commented
> Please have a look.

Done! Now waiting for @sotnikov-s to decide on piping curl to bash :)

2023-08-24 09:36 UTC, sotnikov-s commented on docs/tutorials/cosmwasm_wasmkit.md
> +```
I agree with foxpy on it: I'd like to see links to official website of a product we suggest readers to install because people should use their guidelines which can very in time. the script installation can get outdated whereas a link to official documentation of a product will most likely contain the most modern and up-to-date way to install it.

a funny thing is that in the IBC relayer section we have [the same script installation suggestion](https://github.com/neutron-org/neutron-docs/blob/main/docs/relaying/ibc-relayer.md#install-rust-dependencies) 😝 

fixing this is out of scope of this PR, so I find it acceptable to have it as it is (the curl blah-blah) in both places and fix later. I'll make a note about it

2023-08-24 09:37 UTC, sotnikov-s commented
waiting the frontend launch to be fixed before I approve (discussed it with Udit in DM)

2023-08-24 09:49 UTC, foxpy commented on docs/tutorials/cosmwasm_wasmkit.md
> +```
> a funny thing is that in the IBC relayer section we have [the same script installation suggestion](https://github.com/neutron-org/neutron-docs/blob/main/docs/relaying/ibc-relayer.md#install-rust-dependencies) 😝

bruh!

okay, I will allow it this time since we already have it (and of course I expect it to be deleted sooner or later).

I highly suggest you folks (@udit-gulati and @sotnikov-s) to take a look at this article here to understand why am I so concerned about piping curl to bash: https://sysdig.com/blog/friends-dont-let-friends-curl-bash/

2023-08-24 09:50 UTC, foxpy submitted a review, later dismissed

2023-10-26 10:04 UTC, sotnikov-s approved these changes

2023-10-27 04:49 UTC, foxpy approved these changes

2023-10-31 15:08 UTC, pr0n00gler approved these changes

2023-10-31 15:08 UTC, merged