chore: update neutron links and env vars
neutron-org/neutron-docs pull request #99
Opened 2023-07-14 13:43 UTC by sotnikov-s

2023-07-16 19:09 UTC, foxpy commented on docs/tutorials/integration_tests.md
> +IBC_USDC_DENOM — ibc USDC denom
Maybe we should point out that these IBC denoms are fake?

2023-07-17 08:18 UTC, foxpy approved these changes

2023-07-17 08:18 UTC, foxpy commented on docs/tutorials/integration_tests.md
> +IBC_USDC_DENOM — denom of a native token which is considered as an IBC transferred USDC
Maybe this version will be better, it is up to you to decide:

```suggestion
IBC_ATOM_DENOM — denom of a native token which is used as a fake IBC transferred ATOM
IBC_USDC_DENOM — denom of a native token which is used as a fake IBC transferred USDC
```

2023-07-24 12:40 UTC, pr0n00gler requested changes

2023-07-24 12:40 UTC, pr0n00gler commented on docs/neutron/build-and-run/localnet.md
> +git clone -b v1.0.4-rc1 https://github.com/neutron-org/neutron
We have `v1.4.0` release now. Change it here and above, pls

2023-08-08 11:06 UTC, pr0n00gler approved these changes

2023-08-08 11:07 UTC, merged